Main Page 구현
mywhzy/sorinoeul pull request #1
Opened 2024-01-05 01:52 UTC by mywhzy

- [ ] 헤더 컴포넌트 구현
- [ ] 푸터 컴포넌트 구현
- [ ] 인사말 컴포넌트 구현
- [ ] 앨범 소개 컴포넌트 구현
- [ ] 트랙리스트 컴포넌트 구현
- [ ] 트랙리스트 데이터 JSON 형태로 생성
- [ ] 트랙리스트 데이터 API 형태처럼 받아오는 함수 구현 및 기능 연결
- [ ] 앨범 크레딧 컴포넌트 구현
- [ ] 지원하기 컴포넌트 구현
- [ ] 스트리밍 바로가기 컴포넌트 구현
- [ ] 예배 안내 컴포넌트 구현

2024-01-08 10:27 UTC, ndaemy requested changes
좀 바뀌면 좋을만한 부분이 있어서 Request changes 입니다~

2024-01-08 10:27 UTC, ndaemy commented on src/App.tsx
> +  background: #f8f8f9;
이번에야 간단한 플젝이니까 그냥 해도 큰 이슈는 없는데, 나중에 좀 스케일이 있는 플젝같은거 가면 [stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order) 같은걸 써서 순서도 stylelint 에서 지정하게 만들어두는게 오히려 편할 수도 있어
공부용으로 남겨둠

2024-01-08 10:27 UTC, ndaemy commented on src/assets/data/mockupData.ts
> +    originalSong: undefined,
명시적으로 빈 값을 넣어줄 땐 undefined 가 아니라 null로 하는게 맞을듯

2024-01-08 10:27 UTC, ndaemy commented on src/assets/data/mockupData.ts
> +      'https://drive.google.com/file/d/11AMY2zv5rIq330sxpFD_U74OfVGmRPWc/view?usp=sharing',
요거 firebase 링크로 바꾸는건 아직인건가?

2024-01-08 10:27 UTC, ndaemy commented on src/components/Footer.tsx
> +      <Body2>{COPYRIGHT}</Body2>
Body2 같이 무의미한 숫자는 네이밍에서 제외하는게 나아
나중에 읽기 힘든 코드가 되는 방법 중에 하나라서

2024-01-08 10:27 UTC, ndaemy commented on src/components/Header.tsx
> +  box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
0에 단위 (ex. px) 를 붙여야 하는가는 보통 optional 이라고 하지만, 통일성은 지켜줘야돼
위에서 0에 단위를 안붙였으니 여기도 안붙여야 한다는 얘기

2024-01-08 10:27 UTC, ndaemy commented on src/components/main/AlbumCredit.tsx
> +import { ALBUM_CREDIT, TITLE } from '../../assets/data/constants';
요거 absolute path 썼으면 좀 덜 귀찮았을텐데!

2024-01-08 10:27 UTC, ndaemy commented on src/components/main/GreetingBox.tsx
> +  box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25) inset;
여기도 0px 단위~

2024-01-08 10:27 UTC, ndaemy commented on src/components/main/InformationBox.tsx
> +      <Body2>- {detail}</Body2>
여기도 Body2는 비추
차라리 Title 이랑 Description 으로 하던지!

2024-01-08 10:27 UTC, ndaemy commented on src/components/main/TrackListItem.tsx
> +export const TrackListItem = ({ track }: Track) => {
타입 Track 안에 track 필드가 있으면 말이 안되지
차라리 아래가 말이 될듯

```suggestion
type Track = {
  id: number;
  title: string;
  vocal?: string;
  songWriter?: string;
  originalSong?: string;
  arrangers?: string[];
  soundTrackLink: string;
  scoreLink?: string;
};

export type TrackListItemProps = {
  track: Track;
};

export const TrackListItem = ({ track }: TrackListItemProps) => {

2024-01-11 04:18 UTC, mywhzy commented on src/assets/data/mockupData.ts
> +      'https://drive.google.com/file/d/11AMY2zv5rIq330sxpFD_U74OfVGmRPWc/view?usp=sharing',
파베 링크 나오기 전이라 우선 해두고 json 데이터 때 바꿀까했는데!! 요거 링크 바꾸고 다운로드 기능 연결해야겠다요 ~!

2024-01-11 04:23 UTC, mywhzy commented on src/assets/data/mockupData.ts
> +    originalSong: undefined,
안 그래두 이거 오빠한테 null이랑 undefined 중에 뭐가 이 케이스에서 더 적절한 거냐고 물어보려했는데!! 첨에 null로 했다가 map 돌릴 때 내가 지정한 type에서 | null로 지정을 안 해줘서인지 에러 떠서 일단 undefined로 바꾼건데 다시 바꿔보겠습니당 이거 내가 json 형태로 데이터 바꾸고 한 번 더 피드백 받을게욤 ~,~

2024-01-11 04:24 UTC, mywhzy commented on src/components/Header.tsx
> +  box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
오엠쥐... 그림자는 피그마 그대로 하다가 깜빡쓰했다.. 감사합니닷

2024-01-11 06:12 UTC, mywhzy commented on src/components/main/TrackListItem.tsx
> +export const TrackListItem = ({ track }: Track) => {
이거 props가 너무 많기두 하고... 애초에 데이터 객체로 받아오면 한 번에 객체를 넘겨서 받으려구 했던건데 호호... 내가 봐도 너무 끼워맞추는 식의 코드라구 할 수 있죠 음하하..

2024-01-11 06:24 UTC, mywhzy commented on src/components/main/AlbumCredit.tsx
> +import { ALBUM_CREDIT, TITLE } from '../../assets/data/constants';
인정이여... 그냥 세팅 한 번 하까... 안 되겠다 하고 오겠읍니다.

2024-01-12 01:49 UTC, mywhzy commented on src/components/Footer.tsx
> +      <Body2>{COPYRIGHT}</Body2>
저도 동의하는 부분이기에 바꾸는 중이빈당 다 동일한 폰트 스타일이 적용돼서 약간 타이포그래피 느낌으로 생각한건데 같은 스타일인데 쓰임이 다른 경우 어떻게 네이밍을 통합해야할지 고민,, 그렇다고 네이밍 맞춰 스타일 상속받는 빈 컴포넌트를 만들구 싶진 않구요 🧐

2024-01-14 13:30 UTC, merged